### ISSUE TITLE
Add a shade plugin to support data migration as it related to data model v3.1 update

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/java-fedora-client#54]
0.5FE

**Comment by birkland** [comment]
This allows clients (such as a data migrator) to load old java clients (which can read the old model) and new java clients (which can use the new model) simultaneously, by prefixing all classes in the old (shaded) client with a version number.

    import org.dataconservancy.pass.model.Submission;
    import org.dataconservancy.pass.model.v2_3.Submission;
