### ISSUE TITLE
Update  and cut new release to add support for new data model changes

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/java-fedora-client#87]
- [x] Add `draft` as a new value for submissionStatus
- [x] Add support for Submission.effectivePolicies (new field)
- [x] Add support for Repository.schema (new field)
- [x] Update `SubmissionStatusCalculator` to account for submissions under `draft` status
- [x] Cut a new release for the client

**Comment by emetsger** [comment]
Release cut, and release artifacts promoted to Maven Central.  Should see something at http://repo1.maven.org/maven2/org/dataconservancy/pass/pass-client/0.5.3/ as the mirrors update.
